### ISSUE TITLE
figures in pages/sol/strain are out of order.

### ISSUE THREAD

**Issue by tfg250** [IllinoisRef/mechref#16]
Please take a look at the figures on the strain page, some show in the wrong locations, (i.e. next to text that describes something else). These figures seem in the wrong places: "shear strain", "extensometer.jpg", "True strain"

additionaly, the figures "strainGauge", "VibratingWire" and "dic" appear before their corresponding section heading, seems like they should appear after the section heading.

**Comment by jcrayb** [comment]
It seems that for some reason all the images were shifted by 1 position, i.e. the Image 3 contained the link for Image 2, etc. Thanks for letting me know. I'll have a second look at the other pages as well, since these were all automatically converted, it may be that this is an issue in every 251 page. I'll keep this open until I confirm that this is the only affected page.

**Comment by jcrayb** [comment]
Pages to check:
- [ ] Stress
- [ ] Strain
- [ ] Mat. props.
- [ ] Axial load.
- [ ] Torsion
- [ ] VM diags.
- [ ] Bending
- [ ] Trans. shear
- [ ] Pressure vessels
- [ ] Comb. Load.
- [ ] Stress Transf.
- [ ] Failure theories
- [ ] Beam deflect.
- [ ] Buckling

**Comment by mrhoyle2** [comment]
Are these changes pushed to main/the website? If so, please check against the overleaf doc. Strain is still in the wrong order.

**Comment by mrhoyle2** [comment]
The strain changes need to be pushed before the second week of classes btw.

**Comment by jcrayb** [comment]
Ok, it looks like this issue is contained to the strain page. I corrected the image links and will merge them.
